import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
];

const TRANSLATIONS = {
  en: {
    app_name: 'CrisisConnect',
    tagline: 'Emergency Response & Relief Management Platform',
    citizen_portal: 'Citizen Portal',
    emergency_and_aid: 'Emergency & Aid',
    volunteer_to_help: 'Volunteer to Help',
    immediate_emergency_dispatch: 'IMMEDIATE EMERGENCY DISPATCH',
    sos_beacon: 'SOS BEACON',
    tap_for_help: 'Tap for Help',
    trigger_sos: 'Trigger Critical SOS Beacon',
    satellite_link: '24/7 EOC Satellite Link Active',
    gps_transmit_notice: 'Transmits your exact GPS beacon directly to civil defense & nearby rescue squads.',
    confirm_dispatch: 'CONFIRM & DISPATCH NOW',
    cancel: 'Cancel',
    emergency_nature: 'Immediate Emergency Nature / Details (Optional)',
    people_in_danger: 'People in Danger',
    caller_name: 'Caller Name',
    offline_sms_sos: 'Offline SMS SOS',
    gps_ready: 'GPS Ready',
    gps_locked: 'GPS Locked',
    volunteer_pass: 'Digital Pass',
    impact_rewards: 'Impact Rewards',
    rewards_store: 'Volunteer Rewards Store',
    pts: 'Pts',
    create_emergency_request: 'Create Emergency Request',
    create_emergency_desc: 'Request boat rescue, medical aid, drinking water or shelter',
    request_aid: 'Request Aid',
    nav_home: 'Home',
    nav_map: 'Disaster Map',
    nav_incidents: 'Incidents',
    nav_profile: 'Profile',
    nav_logout: 'Logout',
    nav_switch_role: 'Switch Role',
    citizen_login: 'Citizen Login',
    ngo_login: 'NGO Operations Portal',
    authority_login: 'Disaster Authority Portal',
    mobile_phone: 'Registered Mobile Phone',
    password: 'Password',
    keep_signed_in: 'Keep me signed in',
    forgot_password: 'Forgot Password?',
    register_first: 'REGISTER CITIZEN INFO FIRST',
    login_button: 'Verify from Database & Enter Dashboard',
    quick_categories: 'Request Assistance by Category',
    cat_medical: 'Medical',
    cat_rescue: 'Rescue',
    cat_blood: 'Blood',
    cat_oxygen: 'Oxygen',
    cat_medicines: 'Medicines',
    cat_food: 'Water & Food',
    cat_shelter: 'Shelter',
    cat_transportation: 'Transport',
    cat_trapped: 'Trapped in Building',
    karma_points: 'Karma Points',
    active_missions: 'Active Volunteer Missions',
    deploy_volunteer: 'Join Mission',
    official_pass: 'Official Pass',
    language: 'Language',
    select_language: 'Select Language / भाषा चुनें',
  },
  hi: {
    app_name: 'क्राइसिसकनेक्ट',
    tagline: 'आपदा राहत एवं आपातकालीन प्रबंधन प्रणाली',
    citizen_portal: 'नागरिक सहायता कक्ष',
    emergency_and_aid: 'आपातकाल एवं सहायता',
    volunteer_to_help: 'मदद के लिए स्वयंसेवक',
    immediate_emergency_dispatch: 'तत्काल आपातकालीन सहायता प्रेषण',
    sos_beacon: 'आपातकालीन SOS',
    tap_for_help: 'मदद के लिए दबाएं',
    trigger_sos: 'आपातकालीन SOS बीकन चालू करें',
    satellite_link: '24/7 उपग्रह नियंत्रण सक्रिय',
    gps_transmit_notice: 'आपकी सटीक जीपीएस स्थिति सीधे नागरिक सुरक्षा और बचाव दलों को भेजी जाती है।',
    confirm_dispatch: 'पुष्टि करें और तुरंत भेजें',
    cancel: 'रद्द करें',
    emergency_nature: 'आपातकालीन विवरण (वैकल्पिक)',
    people_in_danger: 'खतरे में फंसे लोग',
    caller_name: 'कॉलर का नाम',
    offline_sms_sos: 'ऑफलाइन SMS SOS',
    gps_ready: 'जीपीएस तैयार',
    gps_locked: 'जीपीएस लॉक',
    volunteer_pass: 'डिजिटल पास',
    impact_rewards: 'इनाम वाउचर',
    rewards_store: 'स्वयंसेवक रिवॉर्ड स्टोर',
    pts: 'अंक',
    create_emergency_request: 'आपातकालीन सहायता अनुरोध दर्ज करें',
    create_emergency_desc: 'बचाव नाव, प्राथमिक चिकित्सा, पेयजल अथवा आश्रय का अनुरोध करें',
    request_aid: 'मदद मांगें',
    nav_home: 'होम',
    nav_map: 'आपदा नक्शा',
    nav_incidents: 'घटनाएं',
    nav_profile: 'प्रोफाइल',
    nav_logout: 'लॉगआउट',
    nav_switch_role: 'भूमिका बदलें',
    citizen_login: 'नागरिक लॉगिन',
    ngo_login: 'एनजीओ सहायता पोर्टल',
    authority_login: 'आपदा प्रबंधन प्राधिकरण',
    mobile_phone: 'पंजीकृत मोबाइल नंबर',
    password: 'पासवर्ड',
    keep_signed_in: 'लॉगिन बनाए रखें',
    forgot_password: 'पासवर्ड भूल गए?',
    register_first: 'पहले नागरिक पंजीकरण करें',
    login_button: 'सत्यापित करें और प्रवेश करें',
    quick_categories: 'श्रेणी अनुसार सहायता अनुरोध',
    cat_medical: 'चिकित्सा',
    cat_rescue: 'बचाव नाव',
    cat_blood: 'रक्त सहायता',
    cat_oxygen: 'ऑक्सीजन',
    cat_medicines: 'दवाएं',
    cat_food: 'भोजन व पानी',
    cat_shelter: 'आश्रय',
    cat_transportation: 'परिवहन',
    cat_trapped: 'मलबे में फंसे व्यक्ति',
    karma_points: 'कर्म अंक',
    active_missions: 'सक्रिय राहत अभियान',
    deploy_volunteer: 'अभियान से जुड़ें',
    official_pass: 'आधिकारिक पास',
    language: 'भाषा',
    select_language: 'भाषा चुनें / Select Language',
  },
  mr: {
    app_name: 'क्रायसिसकनेक्ट',
    tagline: 'आपत्ती निवारण व तात्काळ मदत समन्वय व्यासपीठ',
    citizen_portal: 'नागरिक साहाय्य कक्ष',
    emergency_and_aid: 'आपत्कालीन व मदत सेवा',
    volunteer_to_help: 'मदतीसाठी स्वयंसेवक',
    immediate_emergency_dispatch: 'तातडीची आपत्कालीन मदत प्रेषण',
    sos_beacon: 'तातडीची मदत (SOS)',
    tap_for_help: 'मदतीसाठी दाबा',
    trigger_sos: 'तातडीचा SOS अलर्ट पाठवा',
    satellite_link: '२४/७ उपग्रह नियंत्रण कक्ष सक्रिय',
    gps_transmit_notice: 'तुमचे अचूक जीपीएस स्थान थेट नागरी संरक्षण व बचाव पथकाकडे पाठवले जाते.',
    confirm_dispatch: 'खात्री करा आणि त्वरित पाठवा',
    cancel: 'रद्द करा',
    emergency_nature: 'आपत्कालीन माहिती (पर्यायी)',
    people_in_danger: 'धोक्यात असलेल्या व्यक्ती',
    caller_name: 'कॉलरचे नाव',
    offline_sms_sos: 'ऑफलाइन SMS SOS',
    gps_ready: 'जीपीएस सज्ज',
    gps_locked: 'जीपीएस स्थान निश्चित',
    volunteer_pass: 'डिजिटल पास',
    impact_rewards: 'इनाम व्हाउचर',
    rewards_store: 'स्वयंसेवक बक्षीस केंद्र',
    pts: 'गुण',
    create_emergency_request: 'आपत्कालीन मदतीची विनंती नोंदवा',
    create_emergency_desc: 'बचाव बोट, वैद्यकीय मदत, पिण्याचे पाणी अथवा निवारा मागा',
    request_aid: 'मदत मागा',
    nav_home: 'मुख्यपृष्ठ',
    nav_map: 'आपत्ती नकाशा',
    nav_incidents: 'घटना',
    nav_profile: 'माहिती',
    nav_logout: 'बाहेर पडा',
    nav_switch_role: 'भूमिका बदला',
    citizen_login: 'नागरिक लॉगिन',
    ngo_login: 'एनजीओ मदत पोर्टल',
    authority_login: 'आपत्ती नियंत्रण अधिकारी',
    mobile_phone: 'नोंदणीकृत मोबाईल नंबर',
    password: 'पासवर्ड',
    keep_signed_in: 'लॉगिन चालू ठेवा',
    forgot_password: 'पासवर्ड विसरलात?',
    register_first: 'आधी नागरिक नोंदणी करा',
    login_button: 'तपासा आणि डॅशबोर्ड उघडा',
    quick_categories: 'प्रकारानुसार आपत्कालीन मदत',
    cat_medical: 'वैद्यकीय',
    cat_rescue: 'बचाव बोट',
    cat_blood: 'रक्त मदत',
    cat_oxygen: 'ऑक्सिजन',
    cat_medicines: 'औषधे',
    cat_food: 'अन्न व पाणी',
    cat_shelter: 'निवारा',
    cat_transportation: 'वाहतूक',
    cat_trapped: 'इमारतीत अडकलेले लोक',
    karma_points: 'कर्म गुण',
    active_missions: 'सक्रिय मदत मोहिमा',
    deploy_volunteer: 'मोहिमेत सामील व्हा',
    official_pass: 'अधिकृत पास',
    language: 'भाषा',
    select_language: 'भाषा निवडा / Select Language',
  },
  bn: {
    app_name: 'ক্রাইসিসকানেক্ট',
    tagline: 'দুর্যোগ ত্রাণ ও জরুরি উদ্ধার প্ল্যাটফর্ম',
    citizen_portal: 'নাগরিক পোর্টাল',
    emergency_and_aid: 'জরুরি ও ত্রাণ সহায়তা',
    volunteer_to_help: 'স্বেচ্ছাসেবক সাহায্য',
    immediate_emergency_dispatch: 'তাৎক্ষণিক জরুরি উদ্ধার প্রেরণ',
    sos_beacon: 'জরুরি এসওএস',
    tap_for_help: 'সাহায্যের জন্য চাপুন',
    trigger_sos: 'জরুরি এসওএস বীকন চালু করুন',
    satellite_link: '২৪/৭ স্যাটেলাইট সংযোগ সক্রিয়',
    gps_transmit_notice: 'আপনার সঠিক জিপিএস অবস্থান উদ্ধারকারী দলের কাছে সরাসরি পৌঁছে দেওয়া হয়।',
    confirm_dispatch: 'নিশ্চিত করুন এবং পাঠান',
    cancel: 'বাতিল',
    emergency_nature: 'জরুরি পরিস্থিতির বিবরণ (ঐচ্ছিক)',
    people_in_danger: 'বিপদাপন্ন মানুষের সংখ্যা',
    caller_name: 'নাম',
    offline_sms_sos: 'অফলাইন এসএমএস এসওএস',
    gps_ready: 'জিপিএস প্রস্তুত',
    gps_locked: 'জিপিএস অবস্থান লক',
    volunteer_pass: 'ডিজিটাল পাস',
    impact_rewards: 'রিওয়ার্ড ভাউচার',
    rewards_store: 'স্বেচ্ছাসেবক রিওয়ার্ড স্টোর',
    pts: 'পয়েন্ট',
    create_emergency_request: 'জরুরি সাহায্যের আবেদন করুন',
    create_emergency_desc: 'উদ্ধার নৌকা, চিকিৎসা সহায়তা, পানীয় জল বা আশ্রয়ের আবেদন',
    request_aid: 'সাহায্য চান',
    nav_home: 'হোম',
    nav_map: 'দুর্যোগ মানচিত্র',
    nav_incidents: 'ঘটনা',
    nav_profile: 'প্রোফাইল',
    nav_logout: 'লগআউট',
    nav_switch_role: 'ভূমিকা পরিবর্তন',
    citizen_login: 'নাগরিক লগইন',
    ngo_login: 'এনজিও ত্রাণ পোর্টাল',
    authority_login: 'দুর্যোগ কর্তৃপক্ষ পোর্টাল',
    mobile_phone: 'নিবন্ধিত মোবাইল নম্বর',
    password: 'পাসওয়ার্ড',
    keep_signed_in: 'লগইন রাখুন',
    forgot_password: 'পাসওয়ার্ড ভুলে গেছেন?',
    register_first: 'প্রথমে নিবন্ধন করুন',
    login_button: 'যাচাই করে প্রবেশ করুন',
    quick_categories: 'বিভাগ অনুযায়ী জরুরি অনুরোধ',
    cat_medical: 'চিকিৎসা',
    cat_rescue: 'উদ্ধার',
    cat_blood: 'রক্ত',
    cat_oxygen: 'অক্সিজেন',
    cat_medicines: 'ওষুধ',
    cat_food: 'খাবার ও জল',
    cat_shelter: 'আশ্রয়',
    cat_transportation: 'পরিবহন',
    cat_trapped: 'আটকে পড়া ব্যক্তি',
    karma_points: 'কর্ম পয়েন্ট',
    active_missions: 'সक्रिय ত্রাণ মিশন',
    deploy_volunteer: 'মিশনে যোগ দিন',
    official_pass: 'অফিসিয়াল পাস',
    language: 'ভাষা',
    select_language: 'ভাষা নির্বাচন করুন / Select Language',
  },
  ta: {
    app_name: 'கிரைசிஸ்கனெக்ட்',
    tagline: 'பேரிடர் நிவாரணம் மற்றும் அவசர உதவி தளம்',
    citizen_portal: 'குடிமக்கள் தளம்',
    emergency_and_aid: 'அவசர உதவி மற்றும் நிவாரணம்',
    volunteer_to_help: 'தன்னார்வலர் உதவி',
    immediate_emergency_dispatch: 'உடனடி அவசர மீட்புப் பணி',
    sos_beacon: 'அவசர உதவி SOS',
    tap_for_help: 'உதவிக்கு அழுத்தவும்',
    trigger_sos: 'அவசர SOS எச்சரிக்கையை அனுப்பவும்',
    satellite_link: '24/7 செயற்கைக்கோள் இணைப்பு செயலில்',
    gps_transmit_notice: 'உங்கள் சரியான ஜிபிஎஸ் இருப்பிடம் மீட்புக் குழுக்களுக்கு உடனடியாக அனுப்பப்படுகிறது.',
    confirm_dispatch: 'உறுதிப்படுத்தி உடனே அனுப்புங்கள்',
    cancel: 'ரத்துசெய்',
    emergency_nature: 'அவசர விவரம் (விருப்பமானது)',
    people_in_danger: 'ஆபத்தில் உள்ளவர்கள் எண்ணிக்கை',
    caller_name: 'அழைப்பாளர் பெயர்',
    offline_sms_sos: 'ஆஃப்லைன் SMS SOS',
    gps_ready: 'ஜிபிஎஸ் தயார்',
    gps_locked: 'ஜிபிஎஸ் பூட்டப்பட்டது',
    volunteer_pass: 'டிஜிட்டல் பாஸ்',
    impact_rewards: 'வெகுமதி வவுச்சர்கள்',
    rewards_store: 'தன்னார்வலர் வெகுமதி அங்காடி',
    pts: 'புள்ளிகள்',
    create_emergency_request: 'அவசர கோரிக்கை உருவாக்கவும்',
    create_emergency_desc: 'மீட்புப் படகு, மருத்துவ உதவி, குடிநீர் அல்லது தங்குமிடம் கோருங்கள்',
    request_aid: 'உதவி கோருக',
    nav_home: 'முகப்பு',
    nav_map: 'பேரிடர் வரைபடம்',
    nav_incidents: 'நிகழ்வுகள்',
    nav_profile: 'சுயவிவரம்',
    nav_logout: 'வெளியேறு',
    nav_switch_role: 'பொறுப்பை மாற்று',
    citizen_login: 'குடிமக்கள் உள்நுழைவு',
    ngo_login: 'தொண்டு நிறுவன போர்டல்',
    authority_login: 'பேரிடர் மேலாண்மை ஆணையம்',
    mobile_phone: 'பதிவுசெய்யப்பட்ட மொபைல் எண்',
    password: 'கடவுச்சொல்',
    keep_signed_in: 'உள்நுழைந்து இருக்கவும்',
    forgot_password: 'கடவுச்சொல் மறந்துவிட்டதா?',
    register_first: 'முதலில் பதிவு செய்யவும்',
    login_button: 'சரிபார்த்து உள்நுழையவும்',
    quick_categories: 'பிரிவு வாரியாக உதவி கோருங்கள்',
    cat_medical: 'மருத்துவம்',
    cat_rescue: 'மீட்பு',
    cat_blood: 'இரத்தம்',
    cat_oxygen: 'ஆக்சிஜன்',
    cat_medicines: 'மருந்துகள்',
    cat_food: 'உணவு & குடிநீர்',
    cat_shelter: 'தங்குமிடம்',
    cat_transportation: 'போக்குவரத்து',
    cat_trapped: 'சிக்கியவர்கள்',
    karma_points: 'கர்ம புள்ளிகள்',
    active_missions: 'செயலில் உள்ள பணிகள்',
    deploy_volunteer: 'பணியில் இணையுங்கள்',
    official_pass: 'அதிகாரப்பூர்வ பாஸ்',
    language: 'மொழி',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும் / Select Language',
  },
  gu: {
    app_name: 'ક્રાઈસિસકનેક્ટ',
    tagline: 'આપત્તિ રાહત અને કટોકટી વ્યવસ્થાપન પ્લેટફોર્મ',
    citizen_portal: 'નાગરિક સહાય કેન્દ્ર',
    emergency_and_aid: 'કટોકટી અને સહાય સેવા',
    volunteer_to_help: 'મદદ માટે સ્વયંસેવક',
    immediate_emergency_dispatch: 'તાત્કાલિક કટોકટી સહાય રવાનગી',
    sos_beacon: 'કટોકટી SOS',
    tap_for_help: 'મદદ માટે દબાવો',
    trigger_sos: 'કટોકટી SOS બીકન શરૂ કરો',
    satellite_link: '૨૪/૭ ઉપગ્રહ લિંક સક્રિય',
    gps_transmit_notice: 'તમારું ચોક્કસ જીપીએસ સ્થાન સીધું નાગરિક સંરક્ષણ અને બચાવ ટુકડીને મોકલવામાં આવે છે.',
    confirm_dispatch: 'ખાતરી કરો અને તરત મોકલો',
    cancel: 'રદ કરો',
    emergency_nature: 'કટોકટી વિગત (વૈકલ્પિક)',
    people_in_danger: 'જોખમમાં મુકાયેલા લોકો',
    caller_name: 'કોલરનું નામ',
    offline_sms_sos: 'ઓફલાઇન SMS SOS',
    gps_ready: 'જીપીએસ તૈયાર',
    gps_locked: 'જીપીએસ સ્થાન નિશ્ચિત',
    volunteer_pass: 'ડિજિટલ પાસ',
    impact_rewards: 'ઇનામ વાઉચર',
    rewards_store: 'સ્વયંસેવક રિવોર્ડ સ્ટોર',
    pts: 'પોઈન્ટ્સ',
    create_emergency_request: 'કટોકટી સહાય વિનંતી નોંધાવો',
    create_emergency_desc: 'બચાવ બોટ, તબીબી સહાય, પીવાનું પાણી કે આશ્રયની વિનંતી કરો',
    request_aid: 'સહાય મેળવો',
    nav_home: 'મુખ્યપૃષ્ઠ',
    nav_map: 'આપત્તિ નકશો',
    nav_incidents: 'ઘટનાઓ',
    nav_profile: 'પ્રોફાઇલ',
    nav_logout: 'લોગ આઉટ',
    nav_switch_role: 'ભૂમિકા બદલો',
    citizen_login: 'નાગરિક લોગિન',
    ngo_login: 'એનજીઓ સહાય પોર્ટલ',
    authority_login: 'આપત્તિ વ્યવસ્થાપન સત્તામંડળ',
    mobile_phone: 'નોંધાયેલ મોબાઈલ નંબર',
    password: 'પાસવર્ડ',
    keep_signed_in: 'લોગિન ચાલુ રાખો',
    forgot_password: 'પાસવર્ડ ભૂલી ગયા છો?',
    register_first: 'પહેલા નાગરિક નોંધણી કરો',
    login_button: 'ચકાસો અને પ્રવેશ કરો',
    quick_categories: 'શ્રેણી મુજબ કટોકટી વિનંતી',
    cat_medical: 'તબીબી',
    cat_rescue: 'બચાવ',
    cat_blood: 'રક્ત સહાય',
    cat_oxygen: 'ઓક્સિજન',
    cat_medicines: 'દવાઓ',
    cat_food: 'ખોરાક અને પાણી',
    cat_shelter: 'આશ્રય',
    cat_transportation: 'પરિવહન',
    cat_trapped: 'મકાનમાં ફસાયેલા લોકો',
    karma_points: 'કર્મ પોઇન્ટ્સ',
    active_missions: 'સક્રિય રાહત અભિયાન',
    deploy_volunteer: 'મિશનમાં જોડાઓ',
    official_pass: 'સત્તાવાર પાસ',
    language: 'ભાષા',
    select_language: 'ભાષા પસંદ કરો / Select Language',
  },
};

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    try {
      return localStorage.getItem('crisisconnect_language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = (langCode) => {
    setCurrentLang(langCode);
    try {
      localStorage.setItem('crisisconnect_language', langCode);
    } catch {}
  };

  const t = (key) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'en',
      setLanguage: () => {},
      t: (key) => key,
      languages: LANGUAGES,
    };
  }
  return context;
}
