import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
];

const TRANSLATIONS = {
  en: {
    app_name: 'CrisisConnect',
    tagline: 'Emergency Response & Relief Management Platform',
    select_language: 'Select Language / भाषा चुनें',
    database_online: 'Emergency Response Network Active',
    toll_free_hotline: 'Toll-Free Emergency Hotline: 112',
    surveillance_active: 'Surveillance Active: CrisisConnect Rapid Response Network',
    view_map: 'View on Map',
    map_arrow: 'Map →',

    // Public SOS on Login
    public_sos_banner_title: '🚨 EMERGENCY SOS (NO LOGIN REQUIRED)',
    public_sos_banner_subtitle: 'Auto-detects GPS & AI routes to designated authority',
    no_login_needed: 'NO LOGIN REQUIRED',
    public_sos_title: 'Immediate Public SOS Beacon',
    public_sos_desc: 'Device GPS automatically locked & sent to response forces',
    what_is_situation: 'What is Your Emergency Situation?',
    ai_auto_routes: 'AI Auto-Routes to Authority',
    type_situation_placeholder: 'Type what happened (e.g. 3 people trapped in rising flood on 2nd floor, water rising fast)',
    or_tap_preset: 'Or Tap a Quick Emergency Situation:',
    preset_flood: '🌊 Flood Water Rising Rapidly',
    preset_fire: '🔥 Massive Fire / Gas Leak',
    preset_medical: '🏥 Severe Bleeding / Medical Emergency',
    preset_collapse: '🏚️ Building / Wall Collapsed',
    ai_dispatch_button: '🚨 AI DISPATCH TO DESIGNATED AUTHORITY',
    ai_analyzing_dispatch: 'AI CLASSIFYING & DISPATCHING TO AUTHORITIES...',
    sos_broadcasted_success: 'CRITICAL SOS BEACON BROADCASTED!',
    sos_success_desc: 'Your situation has been analyzed by AI and dispatched directly to the official response agency.',
    assigned_force: '🤖 AI ASSIGNED EMERGENCY FORCE',
    critical_priority: 'CRITICAL PRIORITY',
    response_sla: 'Response SLA',
    tracking_beacon: 'Tracking Beacon',
    close_window: 'Close Window',
    call_hotline: 'Call Hotline',

    // Role Selectors
    select_role_prompt: 'Select Your Role to Enter:',
    role_citizen: 'Citizen',
    role_ngo: 'NGO Org',
    role_authority: 'Authority',

    // Citizen Login Tab
    citizen_login_title: 'Citizen Login',
    citizen_login_subtitle: 'Register profile first or login with verified phone',
    new_citizen_prompt: 'New Citizen? Register in Database First:',
    new_citizen_desc: 'Save your name, medical notes & ICE emergency contact to the disaster registry.',
    btn_register_first: 'REGISTER CITIZEN INFO FIRST',
    mobile_phone_label: 'Registered Mobile Phone',
    mobile_phone_placeholder: '10-digit mobile number (e.g. 9850422491)',
    password_label: 'Password',
    password_placeholder: 'Enter your password',
    keep_signed_in: 'Keep me signed in',
    forgot_password: 'Forgot Password?',
    btn_login: 'Verify User & Enter Dashboard',
    verifying_login: 'Verifying with Database...',
    demo_badge: 'Demo Account',
    demo_note: 'Tap to auto-fill credentials for',

    // NGO Login Tab
    ngo_login_title: 'NGO Operations Portal',
    ngo_login_subtitle: 'Manage field volunteer squads, rescue missions & relief donations',
    ngo_org_label: 'Registered Relief Organization',
    ngo_officer_label: 'Coordinator / Lead Name',
    ngo_officer_placeholder: 'Your name or volunteer badge',
    ngo_login_btn: 'Enter NGO Relief Command',

    // Authority Login Tab
    authority_login_title: 'Disaster Authority Portal',
    authority_login_subtitle: 'Emergency Operations Center (EOC) • Multi-Agency Command',
    auth_agency_label: 'Select Your Response Force',
    auth_dept_label: 'Specialized Agency / Unit',
    auth_badge_label: 'Officer Badge / Service ID',
    auth_pin_label: 'Security Authorization PIN',
    auth_login_btn: 'Enter Authority Command Center',

    // User Dashboard
    citizen_portal: 'Citizen Portal',
    emergency_and_aid: 'Emergency & Aid',
    volunteer_to_help: 'Volunteer to Help',
    pts: 'Pts',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'Test Alert',
    immediate_emergency_dispatch: 'IMMEDIATE EMERGENCY DISPATCH',
    sos_beacon: 'SOS BEACON',
    tap_for_help: 'Tap for Help',
    trigger_sos: 'Trigger Critical SOS Beacon',
    satellite_link: '24/7 EOC Satellite Link Active',
    gps_transmit_notice: 'Transmits your exact GPS beacon directly to civil defense & nearby rescue squads.',
    confirm_dispatch: 'CONFIRM & DISPATCH NOW',
    cancel: 'Cancel',
    emergency_nature: 'Immediate Emergency Nature / Details (Optional)',
    people_in_danger: 'People in Danger',
    caller_name: 'Caller Name',
    gps_ready: 'GPS Ready',
    gps_locked: 'GPS Locked',
    create_emergency_request: 'Create Emergency Request',
    create_emergency_desc: 'Request boat rescue, medical aid, drinking water or shelter',
    active_incident_in_progress: 'Active Incident in Progress',
    track_incident_status: 'Track Incident Status & Updates',
    quick_categories: 'Request Assistance by Category',
    report_need: 'Report need →',
    civil_defense_advisories: 'Civil Defense Advisories',
    nearest_shelters: 'Nearest Safe Evacuation Shelters',
    shelter_capacity: 'Capacity',
    call_btn: 'Call',

    // Volunteering Hub
    responders_hub_title: 'Community Disaster Responders Hub',
    responders_hub_desc: 'When disaster strikes, local citizens save lives. If you are in a safe, dry zone, sign up below to assist responding NGOs and local authorities with food supply, medical triage, or rescue support.',
    my_active_missions: 'My Active Deployed Missions',
    verified_responder: 'Verified Responder',
    ready_for_duty: 'Ready for Duty',
    view_official_pass: 'View Official Pass',
    call_lead: 'Call Lead',
    rewards_store_title: 'Volunteer Rewards Store',
    rewards_store_desc: 'Karma Points earned! Redeem Apollo, BigBasket & Uber vouchers.',
    rewards_btn: 'Vouchers →',
    available_missions: 'Available Community Aid Missions',
    sign_up_mission: 'Join Mission (+50 Karma)',
    registered_badge: 'Enrolled ✓',

    // Navigation
    nav_home: 'Home',
    nav_map: 'Disaster Map',
    nav_request_aid: 'Request Aid',
    nav_incidents: 'Incidents',
    nav_profile: 'Profile',
    nav_command: 'Command',
    nav_verify_queue: 'Verify Queue',
    nav_relief_ops: 'Relief Ops',
    nav_feed: 'Feed',
    nav_switch: 'Switch',

    // Categories
    cat_medical: 'Medical Aid',
    cat_rescue: 'Rescue Boat',
    cat_blood: 'Blood Supply',
    cat_oxygen: 'Oxygen Cylinders',
    cat_medicines: 'Medicines',
    cat_food: 'Water & Food',
    cat_shelter: 'Safe Shelter',
    cat_transportation: 'Emergency Transport',
  },

  hi: {
    app_name: 'क्राइसिसकनेक्ट',
    tagline: 'आपदा राहत एवं आपातकालीन प्रबंधन प्रणाली',
    select_language: 'भाषा चुनें / Select Language',
    database_online: 'आपदा डेटाबेस सक्रिय है',
    toll_free_hotline: 'टोल-फ्री आपातकालीन हेल्पलाइन: 112',
    surveillance_active: 'सक्रिय निगरानी: क्राइसिसकनेक्ट त्वरित प्रतिक्रिया तंत्र',
    view_map: 'नक्शे पर देखें',
    map_arrow: 'नक्शा →',

    // Public SOS on Login
    public_sos_banner_title: '🚨 आपातकालीन SOS (लॉगिन की आवश्यकता नहीं)',
    public_sos_banner_subtitle: 'जीपीएस स्वतः पहचानता है व उचित आपदा बल को भेजता है',
    no_login_needed: 'लॉगिन की आवश्यकता नहीं',
    public_sos_title: 'तत्काल सार्वजनिक SOS बीकन',
    public_sos_desc: 'डिवाइस का जीपीएस स्वतः लॉक होकर आपदा नियंत्रण कक्ष को जाता है',
    what_is_situation: 'आपकी आपातकालीन स्थिति क्या है?',
    ai_auto_routes: 'एआई द्वारा संबंधित विभाग को स्वतः प्रेषण',
    type_situation_placeholder: 'स्थिति लिखें (उदा. दूसरी मंजिल पर 3 लोग फंसे हैं, बाढ़ का पानी तेजी से बढ़ रहा है)',
    or_tap_preset: 'या तत्काल स्थिति का चयन करें:',
    preset_flood: '🌊 बाढ़ का पानी तेजी से बढ़ रहा है',
    preset_fire: '🔥 भीषण आग / गैस रिसाव',
    preset_medical: '🏥 गंभीर चोट / बेहोश मरीज',
    preset_collapse: '🏚️ इमारत / दीवार ढह गई',
    ai_dispatch_button: '🚨 संबंधित आपदा दल को तुरंत भेजें',
    ai_analyzing_dispatch: 'एआई विश्लेषण व आपदा बल को प्रेषण जारी...',
    sos_broadcasted_success: 'आपातकालीन SOS बीकन प्रसारित हुआ!',
    sos_success_desc: 'आपकी स्थिति का एआई द्वारा विश्लेषण कर तुरंत आधिकारिक बचाव दल को भेज दिया गया है।',
    assigned_force: '🤖 एआई द्वारा नियुक्त आपातकालीन बल',
    critical_priority: 'अति-गंभीर प्राथमिकता',
    response_sla: 'अनुमानित प्रतिक्रिया समय',
    tracking_beacon: 'ट्रैकिंग कोड',
    close_window: 'विंडो बंद करें',
    call_hotline: 'हेल्पलाइन पर कॉल करें',

    // Role Selectors
    select_role_prompt: 'प्रवेश हेतु अपनी भूमिका चुनें:',
    role_citizen: 'नागरिक',
    role_ngo: 'एनजीओ संस्था',
    role_authority: 'प्रशासन',

    // Citizen Login Tab
    citizen_login_title: 'नागरिक लॉगिन',
    citizen_login_subtitle: 'पहले डेटाबेस में पंजीकरण करें या पंजीकृत मोबाइल से लॉगिन करें',
    new_citizen_prompt: 'नए नागरिक? पहले पंजीकरण करें:',
    new_citizen_desc: 'अपना नाम, चिकित्सा विवरण व आपातकालीन संपर्क आपदा रजिस्टर में सुरक्षित करें।',
    btn_register_first: 'पहले नागरिक विवरण पंजीकृत करें',
    mobile_phone_label: 'पंजीकृत मोबाइल नंबर',
    mobile_phone_placeholder: '10 अंकों का मोबाइल नंबर (उदा. 9850422491)',
    password_label: 'पासवर्ड',
    password_placeholder: 'अपना पासवर्ड दर्ज करें',
    keep_signed_in: 'लॉगिन बनाए रखें',
    forgot_password: 'पासवर्ड भूल गए?',
    btn_login: 'डेटाबेस से सत्यापित करें व प्रवेश करें',
    verifying_login: 'डेटाबेस से जांच हो रही है...',
    demo_badge: 'डेमो खाता',
    demo_note: 'स्वतः क्रेडेंशियल भरने के लिए टैप करें:',

    // NGO Login Tab
    ngo_login_title: 'एनजीओ राहत संचालन पोर्टल',
    ngo_login_subtitle: 'स्वयंसेवक दल, बचाव अभियान और खाद्य राहत सामग्री का प्रबंधन करें',
    ngo_org_label: 'पंजीकृत राहत संगठन',
    ngo_officer_label: 'समन्वयक / अधिकारी का नाम',
    ngo_officer_placeholder: 'अपना नाम या बैज नंबर दर्ज करें',
    ngo_login_btn: 'एनजीओ राहत केंद्र में प्रवेश करें',

    // Authority Login Tab
    authority_login_title: 'आपदा प्रबंधन प्राधिकरण पोर्टल',
    authority_login_subtitle: 'आपातकालीन नियंत्रण कक्ष (EOC) • अंतर-विभागीय कमान',
    auth_agency_label: 'अपना आपदा बचाव बल चुनें',
    auth_dept_label: 'विशेषज्ञ एजेंसी / इकाई',
    auth_badge_label: 'अधिकारी बैज / सेवा आईडी',
    auth_pin_label: 'सुरक्षा प्राधिकरण पिन',
    auth_login_btn: 'नियंत्रण कक्ष में प्रवेश करें',

    // User Dashboard
    citizen_portal: 'नागरिक सहायता कक्ष',
    emergency_and_aid: 'आपातकाल एवं सहायता',
    volunteer_to_help: 'मदद के लिए स्वयंसेवक',
    pts: 'अंक',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'परीक्षण अलर्ट',
    immediate_emergency_dispatch: 'तत्काल आपातकालीन सहायता प्रेषण',
    sos_beacon: 'आपातकालीन SOS',
    tap_for_help: 'मदद के लिए दबाएं',
    trigger_sos: 'आपातकालीन SOS बीकन चालू करें',
    satellite_link: '24/7 उपग्रह नियंत्रण सक्रिय',
    gps_transmit_notice: 'आपकी सटीक जीपीएस स्थिति सीधे नागरिक सुरक्षा और बचाव दलों को भेजी जाती है।',
    confirm_dispatch: 'पुष्टि करें और तुरंत भेजें',
    cancel: 'रद्द करें',
    emergency_nature: 'आपातकालीन विवरण (वैकल्पिक)',
    people_in_danger: 'खतरे में फंसे लोग',
    caller_name: 'कॉलर का नाम',
    gps_ready: 'जीपीएस तैयार',
    gps_locked: 'जीपीएस लॉक',
    create_emergency_request: 'आपातकालीन सहायता अनुरोध दर्ज करें',
    create_emergency_desc: 'बचाव नाव, प्राथमिक चिकित्सा, पेयजल अथवा आश्रय का अनुरोध करें',
    active_incident_in_progress: 'सक्रिय आपातकालीन घटना जारी',
    track_incident_status: 'घटना की स्थिति व बचाव प्रगति देखें',
    quick_categories: 'श्रेणी अनुसार सहायता अनुरोध',
    report_need: 'अनुरोध करें →',
    civil_defense_advisories: 'नागरिक सुरक्षा चेतावनियां',
    nearest_shelters: 'निकटतम सुरक्षित राहत शिविर',
    shelter_capacity: 'क्षमता',
    call_btn: 'कॉल करें',

    // Volunteering Hub
    responders_hub_title: 'समुदायिक आपदा स्वयंसेवक केंद्र',
    responders_hub_desc: 'आपदा के समय स्थानीय नागरिक ही सबसे पहले जान बचाते हैं। यदि आप सुरक्षित स्थान पर हैं, तो भोजन वितरण, प्राथमिक चिकित्सा या बचाव कार्य में सहायता हेतु नीचे जुड़ें।',
    my_active_missions: 'मेरे सक्रिय राहत अभियान',
    verified_responder: 'सत्यापित स्वयंसेवक',
    ready_for_duty: 'ड्यूटी हेतु तैयार',
    view_official_pass: 'आधिकारिक डिजिटल पास देखें',
    call_lead: 'प्रमुख को कॉल करें',
    rewards_store_title: 'स्वयंसेवक रिवॉर्ड स्टोर',
    rewards_store_desc: 'कर्म अंक प्राप्त हुए! अपोलो, बिगबास्केट और उबर वाउचर रिडीम करें।',
    rewards_btn: 'वाउचर →',
    available_missions: 'उपलब्ध राहत अभियान',
    sign_up_mission: 'अभियान से जुड़ें (+50 कर्म अंक)',
    registered_badge: 'पंजीकृत ✓',

    // Navigation
    nav_home: 'होम',
    nav_map: 'आपदा नक्शा',
    nav_request_aid: 'मदद मांगें',
    nav_incidents: 'घटनाएं',
    nav_profile: 'प्रोफाइल',
    nav_command: 'कमांड',
    nav_verify_queue: 'सत्यापन सूची',
    nav_relief_ops: 'राहत कार्य',
    nav_feed: 'फीड',
    nav_switch: 'बदलें',

    // Categories
    cat_medical: 'चिकित्सा सहायता',
    cat_rescue: 'बचाव नाव',
    cat_blood: 'रक्त सहायता',
    cat_oxygen: 'ऑक्सीजन सिलेंडर',
    cat_medicines: 'दवाइयां',
    cat_food: 'भोजन व स्वच्छ पानी',
    cat_shelter: 'सुरक्षित आश्रय',
    cat_transportation: 'आपातकालीन वाहन',
  },

  mr: {
    app_name: 'क्रायसिसकनेक्ट',
    tagline: 'आपत्ती निवारण व तात्काळ मदत समन्वय व्यासपीठ',
    select_language: 'भाषा निवडा / Select Language',
    database_online: 'आपत्ती डेटाबेस ऑनलाईन सक्रिय',
    toll_free_hotline: 'टोल-फ्री आपत्कालीन क्रमांक: 112',
    surveillance_active: 'सक्रिय देखरेख: क्रायसिसकनेक्ट जलद प्रतिसाद यंत्रणा',
    view_map: 'नकाशावर पहा',
    map_arrow: 'नकाशा →',

    // Public SOS on Login
    public_sos_banner_title: '🚨 तातडीचा SOS (लॉगिनची गरज नाही)',
    public_sos_banner_subtitle: 'जीपीएस आपोआप घेऊन योग्य त्या यंत्रणेकडे मदत पाठवली जाते',
    no_login_needed: 'लॉगिनची गरज नाही',
    public_sos_title: 'तातडीचा सार्वजनिक SOS बीकन',
    public_sos_desc: 'मोबाईलचे जीपीएस आपोआप नोंदवून बचाव दलाकडे पाठवले जाते',
    what_is_situation: 'तुमची आपत्कालीन परिस्थिती काय आहे?',
    ai_auto_routes: 'एआय द्वारे संबंधित आपत्ती दलाकडे थेट संदेश',
    type_situation_placeholder: 'नेमके काय घडले आहे ते लिहा (उदा. दुसऱ्या मजल्यावर ३ लोक अडकले आहेत, पुराचे पाणी वेगाने वाढत आहे)',
    or_tap_preset: 'किंवा तात्काळ परिस्थिती निवडा:',
    preset_flood: '🌊 पुराचे पाणी वेगाने वाढत आहे',
    preset_fire: '🔥 मोठी आग / गॅस गळती',
    preset_medical: '🏥 गंभीर दुखापत / बेशुद्ध रुग्ण',
    preset_collapse: '🏚️ इमारत / भिंत कोसळली',
    ai_dispatch_button: '🚨 संबंधित आपत्ती दलाकडे तात्काळ पाठवा',
    ai_analyzing_dispatch: 'एआय विश्लेषण व बचाव दलास माहिती पाठवत आहे...',
    sos_broadcasted_success: 'तातडीचा SOS अलर्ट प्रसारित झाला!',
    sos_success_desc: 'तुमच्या परिस्थितीचे एआय द्वारे विश्लेषण होऊन थेट अधिकृत आपत्ती निवारण दलाकडे पाठवले गेले आहे.',
    assigned_force: '🤖 एआय द्वारे नियुक्त बचाव दल',
    critical_priority: 'अति-महत्त्वाची प्राथमिकता',
    response_sla: 'अपेक्षित प्रतिसाद वेळ',
    tracking_beacon: 'ट्रॅकिंग कोड',
    close_window: 'खिडकी बंद करा',
    call_hotline: 'हेल्पलाईनला कॉल करा',

    // Role Selectors
    select_role_prompt: 'प्रवेश करण्यासाठी तुमची भूमिका निवडा:',
    role_citizen: 'नागरिक',
    role_ngo: 'एनजीओ संस्था',
    role_authority: 'प्रशासन',

    // Citizen Login Tab
    citizen_login_title: 'नागरिक लॉगिन',
    citizen_login_subtitle: 'आधी डेटाबेसमध्ये नोंदणी करा किंवा नोंदणीकृत मोबाईलने लॉगिन करा',
    new_citizen_prompt: 'नवीन नागरिक? आधी डेटाबेसमध्ये नोंदणी करा:',
    new_citizen_desc: 'तुमचे नाव, वैद्यकीय नोंदी व आपत्कालीन संपर्क रजिस्टरमध्ये सुरक्षित ठेवा.',
    btn_register_first: 'आधी नागरिक नोंदणी करा',
    mobile_phone_label: 'नोंदणीकृत मोबाईल नंबर',
    mobile_phone_placeholder: '१० अंकी मोबाईल नंबर (उदा. 9850422491)',
    password_label: 'पासवर्ड',
    password_placeholder: 'तुमचा पासवर्ड टाका',
    keep_signed_in: 'लॉगिन चालू ठेवा',
    forgot_password: 'पासवर्ड विसरलात?',
    btn_login: 'डेटाबेस तपासा आणि डॅशबोर्ड उघडा',
    verifying_login: 'डेटाबेस तपासणी सुरू आहे...',
    demo_badge: 'डेमो खाते',
    demo_note: 'माहिती आपोआप भरण्यासाठी येथे दाबा:',

    // NGO Login Tab
    ngo_login_title: 'एनजीओ मदत व बचाव पोर्टल',
    ngo_login_subtitle: 'स्वयंसेवक पथके, बचाव कार्य आणि अन्न-पाणी वाटपाचे व्यवस्थापन करा',
    ngo_org_label: 'नोंदणीकृत मदत संस्था',
    ngo_officer_label: 'समन्वयक / अधिकाऱ्याचे नाव',
    ngo_officer_placeholder: 'तुमचे नाव किंवा स्वयंसेवक ओळख क्रमांक',
    ngo_login_btn: 'एनजीओ नियंत्रण कक्षात प्रवेश करा',

    // Authority Login Tab
    authority_login_title: 'आपत्ती नियंत्रण अधिकारी पोर्टल',
    authority_login_subtitle: 'आपत्कालीन नियंत्रण कक्ष (EOC) • संयुक्त कमान',
    auth_agency_label: 'तुमचे बचाव दल निवडा',
    auth_dept_label: 'विशेष आपत्ती विभाग / तुकडी',
    auth_badge_label: 'अधिकारी बॅज / सेवा क्रमांक',
    auth_pin_label: 'सुरक्षा पिन क्रमांक',
    auth_login_btn: 'कमांड सेंटरमध्ये प्रवेश करा',

    // User Dashboard
    citizen_portal: 'नागरिक साहाय्य कक्ष',
    emergency_and_aid: 'आपत्कालीन व मदत सेवा',
    volunteer_to_help: 'मदतीसाठी स्वयंसेवक',
    pts: 'गुण',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'चाचणी अलर्ट',
    immediate_emergency_dispatch: 'तातडीची आपत्कालीन मदत प्रेषण',
    sos_beacon: 'तातडीची मदत (SOS)',
    tap_for_help: 'मदतीसाठी दाबा',
    trigger_sos: 'तातडीचा SOS अलर्ट पाठवा',
    satellite_link: '२४/७ उपग्रह नियंत्रण कक्ष सक्रिय',
    gps_transmit_notice: 'तुमचे अचूक जीपीएस स्थान थेट नागरी संरक्षण व बचाव पथकाकडे पाठवले जाते.',
    confirm_dispatch: 'खात्री करा आणि त्वरित पाठवा',
    cancel: 'रद्द करा',
    emergency_nature: 'आपत्कालीन माहिती (पर्यायी)',
    people_in_danger: 'धोक्यात असलेल्या व्यक्ती',
    caller_name: 'कॉलरचे नाव',
    gps_ready: 'जीपीएस सज्ज',
    gps_locked: 'जीपीएस स्थान निश्चित',
    create_emergency_request: 'आपत्कालीन मदतीची विनंती नोंदवा',
    create_emergency_desc: 'बचाव बोट, वैद्यकीय मदत, पिण्याचे पाणी अथवा निवारा मागा',
    active_incident_in_progress: 'सक्रिय आपत्कालीन मदत मोहीम सुरू',
    track_incident_status: 'मदतीची सद्यस्थिती व प्रगती पहा',
    quick_categories: 'प्रकारानुसार आपत्कालीन मदत',
    report_need: 'मदत मागा →',
    civil_defense_advisories: 'नागरी संरक्षण इशारे व सूचना',
    nearest_shelters: 'जवळचे सुरक्षित मदत व निवारा छावण्या',
    shelter_capacity: 'जागा क्षमता',
    call_btn: 'कॉल करा',

    // Volunteering Hub
    responders_hub_title: 'समुदाय आपत्ती स्वयंसेवक केंद्र',
    responders_hub_desc: 'आपत्तीच्या वेळी स्थानिक नागरिकच त्वरित धावून येतात. तुम्ही सुरक्षित असाल, तर अन्न वाटप, प्रथमोपचार किंवा बचाव कार्यात मदत करण्यासाठी खाली नोंदणी करा.',
    my_active_missions: 'माझ्या सक्रिय मदत मोहिमा',
    verified_responder: 'प्रमाणित स्वयंसेवक',
    ready_for_duty: 'कर्तव्यासाठी सज्ज',
    view_official_pass: 'अधिकृत डिजिटल पास पहा',
    call_lead: 'प्रमुखांना कॉल करा',
    rewards_store_title: 'स्वयंसेवक बक्षीस केंद्र',
    rewards_store_desc: 'कर्म गुण मिळाले! अपोलो, बिगबास्केट आणि उबेर व्हाउचर मिळवा.',
    rewards_btn: 'व्हाउचर →',
    available_missions: 'उपलब्ध मदत मोहिमा',
    sign_up_mission: 'मोहिमेत सामील व्हा (+५० कर्म गुण)',
    registered_badge: 'नोंदणी झाली ✓',

    // Navigation
    nav_home: 'मुख्यपृष्ठ',
    nav_map: 'आपत्ती नकाशा',
    nav_request_aid: 'मदत मागा',
    nav_incidents: 'घटना',
    nav_profile: 'माहिती',
    nav_command: 'कमांड',
    nav_verify_queue: 'पडताळणी यादी',
    nav_relief_ops: 'राहत कार्य',
    nav_feed: 'फीड',
    nav_switch: 'बदला',

    // Categories
    cat_medical: 'वैद्यकीय मदत',
    cat_rescue: 'बचाव बोट',
    cat_blood: 'रक्त मदत',
    cat_oxygen: 'ऑक्सिजन सिलेंडर',
    cat_medicines: 'औषधे',
    cat_food: 'अन्न व पिण्याचे पाणी',
    cat_shelter: 'सुरक्षित निवारा',
    cat_transportation: 'आपत्कालीन वाहन',
  },

  bn: {
    app_name: 'ক্রাইসিসকানেক্ট',
    tagline: 'দুর্যোগ ত্রাণ ও জরুরি উদ্ধার প্ল্যাটফর্ম',
    select_language: 'ভাষা নির্বাচন করুন / Select Language',
    database_online: 'দুর্যোগ ডেটাবেস সক্রিয়',
    toll_free_hotline: 'টোল-ফ্রি জরুরি হেল্পলাইন: ১১২',
    surveillance_active: 'জরুরি নজরদারি সক্রিয়',
    view_map: 'মানচিত্রে দেখুন',
    map_arrow: 'মানচিত্র →',
    public_sos_banner_title: '🚨 জরুরি এসওএস (লগইন প্রয়োজন নেই)',
    public_sos_banner_subtitle: 'জিপিএস অবস্থান শনাক্ত করে সরাসরি উদ্ধারকারী দলকে পাঠায়',
    no_login_needed: 'লগইন প্রয়োজন নেই',
    public_sos_title: 'তাৎক্ষণিক জরুরি এসওএস বীকন',
    public_sos_desc: 'ডিভাইস জিপিএস লক করে সরাসরি উদ্ধারকারী বাহিনীকে পাঠানো হচ্ছে',
    what_is_situation: 'আপনার জরুরি পরিস্থিতি কী?',
    ai_auto_routes: 'এআই স্বয়ংক্রিয়ভাবে নির্দিষ্ট সংস্থায় পাঠাবে',
    type_situation_placeholder: 'পরিস্থিতি লিখুন (যেমন: ২য় তলায় ৩ জন আটকে আছে, বন্যার পানি দ্রুত বাড়ছে)',
    or_tap_preset: 'অথবা সরাসরি বেছে নিন:',
    preset_flood: '🌊 বন্যার পানি দ্রুত বাড়ছে',
    preset_fire: '🔥 ভয়াবহ আগুন / গ্যাস লিক',
    preset_medical: '🏥 গুরুতর আঘাত / অজ্ঞান রোগী',
    preset_collapse: '🏚️ বাড়ি / দেয়াল ধসে পড়েছে',
    ai_dispatch_button: '🚨 নির্দিষ্ট সংস্থায় জরুরি প্রেরণ',
    ai_analyzing_dispatch: 'এআই বিশ্লেষণ করে নির্দিষ্ট বাহিনীকে পাঠাচ্ছে...',
    sos_broadcasted_success: 'জরুরি এসওএস সফলভাবে পাঠানো হয়েছে!',
    sos_success_desc: 'আপনার পরিস্থিতি এআই বিশ্লেষণ করে উদ্ধারকারী সংস্থাকে পাঠানো হয়েছে।',
    assigned_force: '🤖 নিযুক্ত উদ্ধারকারী সংস্থা',
    critical_priority: 'সর্বোচ্চ অগ্রাধিকার',
    response_sla: 'আনুমানিক পৌঁছানোর সময়',
    tracking_beacon: 'ট্র্যাকিং কোড',
    close_window: 'উইন্ডো বন্ধ করুন',
    call_hotline: 'হেল্পলাইনে কল করুন',
    select_role_prompt: 'প্রবেশ করতে ভূমিকা নির্বাচন করুন:',
    role_citizen: 'নাগরিক',
    role_ngo: 'এনজিও',
    role_authority: 'কর্তৃপক্ষ',
    citizen_login_title: 'নাগরিক লগইন',
    citizen_login_subtitle: 'প্রথমে নিবন্ধন করুন বা নিবন্ধিত মোবাইল দিয়ে লগইন করুন',
    new_citizen_prompt: 'নতুন নাগরিক? প্রথমে ডেটাবেসে নিবন্ধন করুন:',
    new_citizen_desc: 'আপনার নাম, চিকিৎসা তথ্য এবং জরুরি যোগাযোগ সংরক্ষণ করুন।',
    btn_register_first: 'প্রথমে নাগরিক তথ্য নিবন্ধন করুন',
    mobile_phone_label: 'নিবন্ধিত মোবাইল নম্বর',
    mobile_phone_placeholder: '১০ ডিজিটের মোবাইল নম্বর',
    password_label: 'পাসওয়ার্ড',
    password_placeholder: 'আপনার পাসওয়ার্ড লিখুন',
    keep_signed_in: 'লগইন রাখুন',
    forgot_password: 'পাসওয়ার্ড ভুলে গেছেন?',
    btn_login: 'যাচাই করে প্রবেশ করুন',
    verifying_login: 'যাচাই করা হচ্ছে...',
    demo_badge: 'ডেমো অ্যাকাউন্ট',
    demo_note: 'স্বয়ংক্রিয়ভাবে তথ্য পূরণ করতে চাপুন:',
    ngo_login_title: 'এনজিও ত্রাণ পোর্টাল',
    ngo_login_subtitle: 'স্বেচ্ছাসেবক দল এবং ত্রাণ সামগ্রী পরিচালনা করুন',
    ngo_org_label: 'নিবন্ধিত ত্রাণ সংস্থা',
    ngo_officer_label: 'সমন্বয়কারী / কর্মকর্তার নাম',
    ngo_officer_placeholder: 'আপনার নাম লিখুন',
    ngo_login_btn: 'এনজিও পোর্টালে প্রবেশ করুন',
    authority_login_title: 'দুর্যোগ কর্তৃপক্ষ পোর্টাল',
    authority_login_subtitle: 'জরুরি অপারেশন কেন্দ্র (EOC)',
    auth_agency_label: 'উদ্ধারকারী বাহিনী নির্বাচন করুন',
    auth_dept_label: 'বিশেষ ইউনিট',
    auth_badge_label: 'অফিসার ব্যাজ আইডি',
    auth_pin_label: 'সিকিউরিটি পিন',
    auth_login_btn: 'কমান্ড সেন্টারে প্রবেশ করুন',
    citizen_portal: 'নাগরিক পোর্টাল',
    emergency_and_aid: 'জরুরি ও ত্রাণ সহায়তা',
    volunteer_to_help: 'স্বেচ্ছাসেবক সাহায্য',
    pts: 'পয়েন্ট',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'টেস্ট এলার্ট',
    immediate_emergency_dispatch: 'তাৎক্ষণিক জরুরি উদ্ধার প্রেরণ',
    sos_beacon: 'জরুরি এসওএস',
    tap_for_help: 'সাহায্যের জন্য চাপুন',
    trigger_sos: 'জরুরি এসওএস বীকন চালু করুন',
    satellite_link: '২৪/৭ স্যাটেলাইট সংযোগ সক্রিয়',
    gps_transmit_notice: 'আপনার সঠিক জিপিএস অবস্থান উদ্ধারকারী দলের কাছে সরাসরি পৌঁছে দেওয়া হয়।',
    confirm_dispatch: 'নিশ্চিত করুন এবং পাঠান',
    cancel: 'বাতিল',
    emergency_nature: 'জরুরি পরিস্থিতির বিবরণ (ঐচ্ছিক)',
    people_in_danger: 'বিপদাপন্ন মানুষের সংখ্যা',
    caller_name: 'নাম',
    gps_ready: 'জিপিএস প্রস্তুত',
    gps_locked: 'জিপিএস অবস্থান লক',
    create_emergency_request: 'জরুরি সাহায্যের আবেদন করুন',
    create_emergency_desc: 'উদ্ধার নৌকা, চিকিৎসা সহায়তা, পানীয় জল বা আশ্রয়ের আবেদন',
    active_incident_in_progress: 'সক্রিয় ঘটনা চলমান',
    track_incident_status: 'উদ্ধারের অগ্রগতি দেখুন',
    quick_categories: 'বিভাগ অনুযায়ী জরুরি অনুরোধ',
    report_need: 'আবেদন করুন →',
    civil_defense_advisories: 'নাগরিক প্রতিরক্ষা সতর্কতা',
    nearest_shelters: 'নিকটতম আশ্রয় কেন্দ্র',
    shelter_capacity: 'ধারণক্ষমতা',
    call_btn: 'কল করুন',
    responders_hub_title: 'দুর্যোগ স্বেচ্ছাসেবক কেন্দ্র',
    responders_hub_desc: 'নিরাপদ স্থানে থাকলে ত্রাণ কার্যক্রমে সাহায্য করতে নিচে যুক্ত হন।',
    my_active_missions: 'আমার সক্রিয় মিশন',
    verified_responder: 'যাচাইকৃত স্বেচ্ছাসেবক',
    ready_for_duty: 'দায়িত্ব পালনে প্রস্তুত',
    view_official_pass: 'অফিসিয়াল পাস দেখুন',
    call_lead: 'নেতাকে কল করুন',
    rewards_store_title: 'স্বেচ্ছাসেবক রিওয়ার্ড স্টোর',
    rewards_store_desc: 'পয়েন্ট অর্জন করেছেন! ভাউচার রিডিম করুন।',
    rewards_btn: 'ভাউচার →',
    available_missions: 'উপলব্ধ মিশন',
    sign_up_mission: 'মিশনে যোগ দিন (+৫০ পয়েন্ট)',
    registered_badge: 'যুক্ত হয়েছেন ✓',
    nav_home: 'হোম',
    nav_map: 'দুর্যোগ মানচিত্র',
    nav_request_aid: 'সাহায্য চান',
    nav_incidents: 'ঘটনা',
    nav_profile: 'প্রোফাইল',
    nav_command: 'কমান্ড',
    nav_verify_queue: 'যাচাই তালিকা',
    nav_relief_ops: 'ত্রাণ কাজ',
    nav_feed: 'ফিড',
    nav_switch: 'পরিবর্তন',
    cat_medical: 'চিকিৎসা সাহায্য',
    cat_rescue: 'উদ্ধার নৌকা',
    cat_blood: 'রক্তের সাহায্য',
    cat_oxygen: 'অক্সিজেন',
    cat_medicines: 'ওষুধ',
    cat_food: 'খাবার ও জল',
    cat_shelter: 'নিরাপদ আশ্রয়',
    cat_transportation: 'জরুরি যান',
  },

  ta: {
    app_name: 'கிரைசிஸ்கனெக்ட்',
    tagline: 'பேரிடர் நிவாரணம் மற்றும் அவசர உதவி தளம்',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும் / Select Language',
    database_online: 'பேரிடர் தகவல் தளம் இயங்குகிறது',
    toll_free_hotline: 'இலவச அவசர உதவி எண்: 112',
    surveillance_active: 'கண்காணிப்பு செயலில் உள்ளது',
    view_map: 'வரைபடத்தில் பார்க்கவும்',
    map_arrow: 'வரைபடம் →',
    public_sos_banner_title: '🚨 உடனடி அவசர உதவி (உள்நுழைவு தேவையில்லை)',
    public_sos_banner_subtitle: 'இருப்பிடத்தை கண்டறிந்து மீட்புக் குழுவுக்கு உடனே அனுப்புகிறது',
    no_login_needed: 'உள்நுழைவு தேவையில்லை',
    public_sos_title: 'உடனடி அவசர உதவி SOS',
    public_sos_desc: 'ஜிபிஎஸ் இருப்பிடம் பூட்டப்பட்டு மீட்புப் படையினருக்கு அனுப்பப்படுகிறது',
    what_is_situation: 'உங்கள் அவசர நிலை என்ன?',
    ai_auto_routes: 'AI மூலம் குறிப்பிட்ட மீட்புக் குழுவுக்கு அனுப்பப்படும்',
    type_situation_placeholder: 'சூழ்நிலையை விவரிக்கவும் (எ.கா: 3 பேர் மாடியில் வெள்ளத்தில் சிக்கியுள்ளனர்)',
    or_tap_preset: 'அல்லது உடனடி தேர்வை அழுத்தவும்:',
    preset_flood: '🌊 வெள்ள நீர் வேகமாக உயருகிறது',
    preset_fire: '🔥 பெரும் தீ / எரிவாயு கசிவு',
    preset_medical: '🏥 தீவிர காயம் / சுயநினைவற்ற நோயாளி',
    preset_collapse: '🏚️ கட்டிடம் / சுவர் இடிந்து விழுந்தது',
    ai_dispatch_button: '🚨 மீட்புக் குழுவுக்கு உடனே அனுப்புங்கள்',
    ai_analyzing_dispatch: 'AI மூலம் ஆய்வு செய்யப்பட்டு அனுப்பப்படுகிறது...',
    sos_broadcasted_success: 'அவசர SOS எச்சரிக்கை அனுப்பப்பட்டது!',
    sos_success_desc: 'உங்கள் நிலைமை ஆய்வு செய்யப்பட்டு அதிகாரப்பூர்வ மீட்புக் குழுவுக்கு அனுப்பப்பட்டுள்ளது.',
    assigned_force: '🤖 நியமிக்கப்பட்ட மீட்புக் குழு',
    critical_priority: 'முக்கிய முன்னுரிமை',
    response_sla: 'எதிர்பார்க்கப்படும் நேரம்',
    tracking_beacon: 'கண்காணிப்பு குறியீடு',
    close_window: 'சாளரத்தை மூடு',
    call_hotline: 'உதவி எண்ணை அழைக்கவும்',
    select_role_prompt: 'உள்நுழைய பொறுப்பைத் தேர்ந்தெடுக்கவும்:',
    role_citizen: 'குடிமக்கள்',
    role_ngo: 'தொண்டு நிறுவனம்',
    role_authority: 'அதிகாரிகள்',
    citizen_login_title: 'குடிமக்கள் உள்நுழைவு',
    citizen_login_subtitle: 'முதலில் பதிவு செய்யவும் அல்லது பதிவுசெய்த எண்ணுடன் நுழையவும்',
    new_citizen_prompt: 'புதிய பயனரா? முதலில் பதிவு செய்யவும்:',
    new_citizen_desc: 'உங்கள் பெயர், மருத்துவ தகவல் மற்றும் அவசர தொடர்பை பதிவு செய்யவும்.',
    btn_register_first: 'முதலில் பதிவு செய்யவும்',
    mobile_phone_label: 'பதிவுசெய்த மொபைல் எண்',
    mobile_phone_placeholder: '10 இலக்க மொபைல் எண்',
    password_label: 'கடவுச்சொல்',
    password_placeholder: 'கடவுச்சொல்லை உள்ளிடவும்',
    keep_signed_in: 'உள்நுழைந்து இருக்கவும்',
    forgot_password: 'கடவுச்சொல் மறந்துவிட்டதா?',
    btn_login: 'சரிபார்த்து உள்நுழையவும்',
    verifying_login: 'சரிபார்க்கப்படுகிறது...',
    demo_badge: 'டெமோ கணக்கு',
    demo_note: 'தானாக நிரப்ப அழுத்தவும்:',
    ngo_login_title: 'தொண்டு நிறுவன போர்டல்',
    ngo_login_subtitle: 'தன்னார்வலர்கள் மற்றும் நிவாரண பணிகளை நிர்வகிக்கவும்',
    ngo_org_label: 'பதிவுசெய்த நிறுவனம்',
    ngo_officer_label: 'ஒருங்கிணைப்பாளர் பெயர்',
    ngo_officer_placeholder: 'உங்கள் பெயரை உள்ளிடவும்',
    ngo_login_btn: 'நிவாரண தளத்திற்குள் நுழைக',
    authority_login_title: 'பேரிடர் மேலாண்மை ஆணையம்',
    authority_login_subtitle: 'அவசர செயல்பாட்டு மையம் (EOC)',
    auth_agency_label: 'படையைத் தேர்ந்தெடுக்கவும்',
    auth_dept_label: 'சிறப்புப் பிரிவு',
    auth_badge_label: 'அதிகாரி அடையாள எண்',
    auth_pin_label: 'பாதுகாப்பு பின்',
    auth_login_btn: 'கட்டுப்பாட்டு மையத்திற்குள் நுழைக',
    citizen_portal: 'குடிமக்கள் தளம்',
    emergency_and_aid: 'அவசர உதவி மற்றும் நிவாரணம்',
    volunteer_to_help: 'தன்னார்வலர் உதவி',
    pts: 'புள்ளிகள்',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'சோதனை எச்சரிக்கை',
    immediate_emergency_dispatch: 'உடனடி அவசர மீட்புப் பணி',
    sos_beacon: 'அவசர உதவி SOS',
    tap_for_help: 'உதவிக்கு அழுத்தவும்',
    trigger_sos: 'அவசர SOS எச்சரிக்கையை அனுப்பவும்',
    satellite_link: '24/7 செயற்கைக்கோள் இணைப்பு செயலில்',
    gps_transmit_notice: 'உங்கள் சரியான ஜிபிஎஸ் இருப்பிடம் மீட்புக் குழுக்களுக்கு உடனடியாக அனுப்பப்படுகிறது.',
    confirm_dispatch: 'உறுதிப்படுத்தி உடனே அனுப்புங்கள்',
    cancel: 'ரத்துசெய்',
    emergency_nature: 'அவசர விவரம் (விருப்பமானது)',
    people_in_danger: 'ஆபத்தில் உள்ளவர்கள் எண்ணிக்கை',
    caller_name: 'அழைப்பாளர் பெயர்',
    gps_ready: 'ஜிபிஎஸ் தயார்',
    gps_locked: 'ஜிபிஎஸ் பூட்டப்பட்டது',
    create_emergency_request: 'அவசர கோரிக்கை உருவாக்கவும்',
    create_emergency_desc: 'மீட்புப் படகு, மருத்துவ உதவி, குடிநீர் அல்லது தங்குமிடம் கோருங்கள்',
    active_incident_in_progress: 'மீட்புப் பணி நடைபெறுகிறது',
    track_incident_status: 'முன்னேற்றத்தைக் கண்காணிக்கவும்',
    quick_categories: 'பிரிவு வாரியாக உதவி கோருங்கள்',
    report_need: 'கோரிக்கை வைக்க →',
    civil_defense_advisories: 'பாதுகாப்பு எச்சரிக்கைகள்',
    nearest_shelters: 'அருகிலுள்ள நிவாரண முகாம்கள்',
    shelter_capacity: 'கொள்ளளவு',
    call_btn: 'அழைக்கவும்',
    responders_hub_title: 'தன்னார்வலர் மீட்பு மையம்',
    responders_hub_desc: 'பாதுகாப்பான இடத்தில் இருந்தால் மற்றவர்களுக்கு உதவ இணையுங்கள்.',
    my_active_missions: 'செயலில் உள்ள பணிகள்',
    verified_responder: 'சான்றளிக்கப்பட்ட தன்னார்வலர்',
    ready_for_duty: 'பணிக்கு தயார்',
    view_official_pass: 'அதிகாரப்பூர்வ பாஸ் பார்க்க',
    call_lead: 'தலைவரை அழைக்கவும்',
    rewards_store_title: 'வெகுமதி அங்காடி',
    rewards_store_desc: 'புள்ளிகள் கிடைத்தன! வவுச்சர்களைப் பெறுங்கள்.',
    rewards_btn: 'வவுச்சர்கள் →',
    available_missions: 'கிடைக்கும் பணிகள்',
    sign_up_mission: 'பணியில் இணையுங்கள் (+50 புள்ளிகள்)',
    registered_badge: 'இணைந்தார் ✓',
    nav_home: 'முகப்பு',
    nav_map: 'பேரிடர் வரைபடம்',
    nav_request_aid: 'உதவி கோருக',
    nav_incidents: 'நிகழ்வுகள்',
    nav_profile: 'சுயவிவரம்',
    nav_command: 'கட்டளை மையம்',
    nav_verify_queue: 'சரிபார்ப்பு பட்டியல்',
    nav_relief_ops: 'நிவாரணப் பணி',
    nav_feed: 'செய்திகள்',
    nav_switch: 'மாற்று',
    cat_medical: 'மருத்துவ உதவி',
    cat_rescue: 'மீட்புப் படகு',
    cat_blood: 'இரத்த உதவி',
    cat_oxygen: 'ஆக்சிஜன் சிலிண்டர்',
    cat_medicines: 'மருந்துகள்',
    cat_food: 'உணவு & குடிநீர்',
    cat_shelter: 'பாதுகாப்பான இடம்',
    cat_transportation: 'அவசர வாகனம்',
  },

  gu: {
    app_name: 'ક્રાઈસિસકનેક્ટ',
    tagline: 'આપત્તિ રાહત અને કટોકટી વ્યવસ્થાપન પ્લેટફોર્મ',
    select_language: 'ભાષા પસંદ કરો / Select Language',
    database_online: 'આપત્તિ ડેટાબેઝ ઓનલાઇન સક્રિય',
    toll_free_hotline: 'ટોલ-ફ્રી કટોકટી હેલ્પલાઇન: ૧૧૨',
    surveillance_active: 'સક્રિય દેખરેખ કાર્યરત છે',
    view_map: 'નકશા પર જુઓ',
    map_arrow: 'નકશો →',
    public_sos_banner_title: '🚨 કટોકટી SOS (લોગિન જરૂરી નથી)',
    public_sos_banner_subtitle: 'GPS શોધીને સંબંધિત રાહત દળને તાત્કાલિક મોકલે છે',
    no_login_needed: 'લોગિન જરૂરી નથી',
    public_sos_title: 'તાત્કાલિક જાહેર SOS બીકન',
    public_sos_desc: 'ડિવાઇસનું GPS આપોઆપ લોક થઈને કંટ્રોલ રૂમને મોકલાય છે',
    what_is_situation: 'તમારી કટોકટીની પરિસ્થિતિ શું છે?',
    ai_auto_routes: 'AI દ્વારા સીધા સંબંધિત વિભાગને રવાનગી',
    type_situation_placeholder: 'પરિસ્થિતિ લખો (દા.ત. બીજા માળે ૩ લોકો ફસાયા છે, પાણી ઝડપથી વધી રહ્યું છે)',
    or_tap_preset: 'અથવા સીધો વિકલ્પ પસંદ કરો:',
    preset_flood: '🌊 પૂરનું પાણી ઝડપથી વધી રહ્યું છે',
    preset_fire: '🔥 ભયાનક આગ / ગેસ ગળતર',
    preset_medical: '🏥 ગંભીર ઇજા / બેભાન દર્દી',
    preset_collapse: '🏚️ મકાન / દીવાલ ધરાશાયી થઈ',
    ai_dispatch_button: '🚨 સંબંધિત રાહત દળને તાત્કાલિક મોકલો',
    ai_analyzing_dispatch: 'AI વિશ્લેષણ અને રાહત દળને રવાનગી ચાલુ...',
    sos_broadcasted_success: 'કટોકટી SOS સફળતાપૂર્વક મોકલાયો!',
    sos_success_desc: 'તમારી પરિસ્થિતિનું AI વિશ્લેષણ કરી સીધા અધિકૃત રાહત દળને મોકલી દેવામાં આવી છે.',
    assigned_force: '🤖 AI દ્વારા નિયુક્ત રાહત દળ',
    critical_priority: 'અતિ-મહત્વપૂર્ણ પ્રાથમિકતા',
    response_sla: 'અપેક્ષિત પ્રતિસાદ સમય',
    tracking_beacon: 'ટ્રેકિંગ કોડ',
    close_window: 'વિન્ડો બંધ કરો',
    call_hotline: 'હેલ્પલાઇન પર કોલ કરો',
    select_role_prompt: 'પ્રવેશ માટે તમારી ભૂમિકા પસંદ કરો:',
    role_citizen: 'નાગરિક',
    role_ngo: 'એનજીઓ',
    role_authority: 'સત્તામંડળ',
    citizen_login_title: 'નાગરિક લોગિન',
    citizen_login_subtitle: 'પહેલાં ડેટાબેઝમાં નોંધણી કરો અથવા નોંધાયેલ નંબરથી લોગિન કરો',
    new_citizen_prompt: 'નવા નાગરિક? પહેલાં નોંધણી કરો:',
    new_citizen_desc: 'તમારું નામ, તબીબી વિગત અને કટોકટી સંપર્ક સુરક્ષિત કરો.',
    btn_register_first: 'પહેલાં નાગરિક નોંધણી કરો',
    mobile_phone_label: 'નોંધાયેલ મોબાઈલ નંબર',
    mobile_phone_placeholder: '૧૦ અંકનો મોબાઈલ નંબર',
    password_label: 'પાસવર્ડ',
    password_placeholder: 'તમારો પાસવર્ડ દાખલ કરો',
    keep_signed_in: 'લોગિન ચાલુ રાખો',
    forgot_password: 'પાસવર્ડ ભૂલી ગયા છો?',
    btn_login: 'ચકાસો અને ડેશબોર્ડમાં પ્રવેશ કરો',
    verifying_login: 'ચકાસણી ચાલુ છે...',
    demo_badge: 'ડેમો ખાતું',
    demo_note: 'માહિતી આપોઆપ ભરવા માટે અહીં દબાવો:',
    ngo_login_title: 'એનજીઓ રાહત પોર્ટલ',
    ngo_login_subtitle: 'સ્વયંસેવક ટુકડીઓ અને સહાય વિતરણ સંભાળો',
    ngo_org_label: 'નોંધાયેલ રાહત સંસ્થા',
    ngo_officer_label: 'સંયોજક / અધિકારીનું નામ',
    ngo_officer_placeholder: 'તમારું નામ દાખલ કરો',
    ngo_login_btn: 'એનજીઓ કેન્દ્રમાં પ્રવેશ કરો',
    authority_login_title: 'આપત્તિ વ્યવસ્થાપન સત્તામંડળ',
    authority_login_subtitle: 'કટોકટી કંટ્રોલ રૂમ (EOC)',
    auth_agency_label: 'તમારું બચાવ દળ પસંદ કરો',
    auth_dept_label: 'ખાસ યુનિટ',
    auth_badge_label: 'અધિકારી બેજ આઈડી',
    auth_pin_label: 'સુરક્ષા પિન',
    auth_login_btn: 'કમાન્ડ સેન્ટરમાં પ્રવેશ કરો',
    citizen_portal: 'નાગરિક સહાય કેન્દ્ર',
    emergency_and_aid: 'કટોકટી અને સહાય સેવા',
    volunteer_to_help: 'મદદ માટે સ્વયંસેવક',
    pts: 'પોઈન્ટ્સ',
    offline_sms_sos: 'SMS SOS',
    test_alert: 'ટેસ્ટ એલર્ટ',
    immediate_emergency_dispatch: 'તાત્કાલિક કટોકટી સહાય રવાનગી',
    sos_beacon: 'કટોકટી SOS',
    tap_for_help: 'મદદ માટે દબાવો',
    trigger_sos: 'કટોકટી SOS બીકન શરૂ કરો',
    satellite_link: '૨૪/૭ ઉપગ્રહ લિંક સક્રિય',
    gps_transmit_notice: 'તમારું ચોક્કસ જીપીએસ સ્થાન સીધું નાગરિક સંરક્ષણ અને બચાવ ટુકડીને મોકલવામાં આવે છે.',
    confirm_dispatch: 'ખાતરી કરો અને તરત મોકલો',
    cancel: 'રદ કરો',
    emergency_nature: 'કટોકટી વિગત (વૈકલ્પિક)',
    people_in_danger: 'જોખમમાં મુકાયેલા લોકો',
    caller_name: 'કોલરનું નામ',
    gps_ready: 'જીપીએસ તૈયાર',
    gps_locked: 'જીપીએસ સ્થાન નિશ્ચિત',
    create_emergency_request: 'કટોકટી સહાય વિનંતી નોંધાવો',
    create_emergency_desc: 'બચાવ બોટ, તબીબી સહાય, પીવાનું પાણી કે આશ્રયની વિનંતી કરો',
    active_incident_in_progress: 'સક્રિય રાહત કામગીરી ચાલુ',
    track_incident_status: 'બચાવ કાર્યની પ્રગતિ જુઓ',
    quick_categories: 'શ્રેણી મુજબ કટોકટી વિનંતી',
    report_need: 'વિનંતી કરો →',
    civil_defense_advisories: 'નાગરિક સંરક્ષણ સૂચનાઓ',
    nearest_shelters: 'નજીકના સુરક્ષિત આશ્રયસ્થાનો',
    shelter_capacity: 'ક્ષમતા',
    call_btn: 'કોલ કરો',
    responders_hub_title: 'સમુદાય આપત્તિ સ્વયંસેવક કેન્દ્ર',
    responders_hub_desc: 'સુરક્ષિત સ્થાને હોવ તો અન્યને મદદ કરવા માટે નીચે જોડાઓ.',
    my_active_missions: 'મારા સક્રિય મિશન',
    verified_responder: 'પ્રમાણિત સ્વયંસેવક',
    ready_for_duty: 'ફરજ માટે તૈયાર',
    view_official_pass: 'સત્તાવાર પાસ જુઓ',
    call_lead: 'મુખ્ય અધિકારીને કોલ કરો',
    rewards_store_title: 'સ્વયંસેવક રિવોર્ડ સ્ટોર',
    rewards_store_desc: 'કર્મ પોઇન્ટ્સ મળ્યા! વાઉચર્સ રિડીમ કરો.',
    rewards_btn: 'વાઉચર્સ →',
    available_missions: 'ઉપલબ્ધ રાહત મિશન',
    sign_up_mission: 'મિશનમાં જોડાઓ (+૫૦ કર્મ પોઇન્ટ્સ)',
    registered_badge: 'નોંધણી થઈ ✓',
    nav_home: 'મુખ્યપૃષ્ઠ',
    nav_map: 'આપત્તિ નકશો',
    nav_request_aid: 'સહાય મેળવો',
    nav_incidents: 'ઘટનાઓ',
    nav_profile: 'પ્રોફાઇલ',
    nav_command: 'કમાન્ડ',
    nav_verify_queue: 'ચકાસણી યાદી',
    nav_relief_ops: 'રાહત કામગીરી',
    nav_feed: 'ફીડ',
    nav_switch: 'બદલો',
    cat_medical: 'તબીબી સહાય',
    cat_rescue: 'બચાવ બોટ',
    cat_blood: 'રક્ત સહાય',
    cat_oxygen: 'ઓક્સિજન સિલિન્ડર',
    cat_medicines: 'દવાઓ',
    cat_food: 'ખોરાક અને સ્વચ્છ પાણી',
    cat_shelter: 'સુરક્ષિત આશ્રય',
    cat_transportation: 'કટોકટી વાહન',
  },
};

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    try {
      return localStorage.getItem('crisisconnect_language') || 'en';
    } catch {
      return 'en';
    }
  });

  const setLanguage = (langCode) => {
    setCurrentLang(langCode);
    try {
      localStorage.setItem('crisisconnect_language', langCode);
    } catch {}
  };

  const t = (key) => {
    const langDict = TRANSLATIONS[currentLang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage, t, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'en',
      setLanguage: () => {},
      t: (key) => key,
      languages: LANGUAGES,
    };
  }
  return context;
}
